"""Binary analysis / reverse engineering tool specs."""

from .._spec import ToolSpec


TOOLS = {
    "strings":     ToolSpec(
            name="strings",
            binary="strings",
            description="Extract printable strings",
            params={"file": None},
            timeout=30,
            builder=lambda p: ["strings", p["file"]],
        ),
    "checksec":     ToolSpec(
            name="checksec",
            binary="checksec",
            description="Binary security features checker",
            params={"file": None},
            timeout=10,
            builder=lambda p: ["checksec", "--file", p["file"]],
        ),
    "objdump":     ToolSpec(
            name="objdump",
            binary="objdump",
            description="Disassemble binary",
            params={"file": None},
            timeout=60,
            builder=lambda p: ["objdump", "-d", p["file"]],
        ),
    "readelf":     ToolSpec(
            name="readelf",
            binary="readelf",
            description="ELF file analyzer",
            params={"file": None},
            timeout=10,
            builder=lambda p: ["readelf", "-a", p["file"]],
        ),
    "gdb":     ToolSpec(
            name="gdb",
            binary="gdb",
            description="GNU debugger",
            params={"file": None},
            timeout=60,
            builder=lambda p: ["gdb", "-batch", "-ex", "info functions", p["file"]],
        ),
    "strace_binary":     ToolSpec(
            name="strace_binary",
            binary="strace",
            description="Trace system calls made by a binary",
            params={"file": None},
            timeout=30,
            category="binary",
            builder=lambda p: ["strace", "-f", "-e", "trace=all", "--", p["file"]],
        ),
    "frida":     ToolSpec(
            name="frida",
            binary="frida",
            description="Dynamic instrumentation toolkit",
            params={"process": None},
            timeout=30,
            builder=lambda p: ["frida", p["process"]],
        ),
    "ghidra":     ToolSpec(
            name="ghidra",
            binary="ghidra",
            description="Binary reverse engineering tool",
            params={"file": None},
            timeout=300,
            builder=lambda p: ["ghidra", p["file"]],
        ),
    "ida":     ToolSpec(
            name="ida",
            binary="ida",
            description="Interactive disassembler",
            params={"file": None},
            timeout=300,
            builder=lambda p: ["ida", p["file"]],
        ),
    "radare2":     ToolSpec(
            name="radare2",
            binary="r2",
            description="Reverse engineering framework",
            params={"file": None},
            timeout=120,
            builder=lambda p: ["r2", "-A", p["file"]],
        ),
    "cutter":     ToolSpec(
            name="cutter",
            binary="cutter",
            description="Radare2 GUI",
            params={"file": None},
            timeout=120,
            builder=lambda p: ["cutter", p["file"]],
        ),
    "angr":     ToolSpec(
            name="angr",
            binary="angr",
            description="Binary analysis engine",
            params={"binary": None},
            timeout=300,
            builder=lambda p: ["angr", p["binary"]],
        ),
    "pwntools":     ToolSpec(
            name="pwntools",
            binary="pwn",
            description="pwntools exploit development utilities (pwn checksec, cyclic, asm)",
            params={"file": None},
            timeout=60,
            risk_level="passive",
            builder=lambda p: ["pwn", "checksec", p["file"]],
        ),
    "ropgadget":     ToolSpec(
            name="ropgadget",
            binary="ROPgadget",
            description="Search ROP gadgets in binaries",
            params={"file": None},
            timeout=120,
            risk_level="passive",
            builder=lambda p: ["ROPgadget", "--binary", p["file"]],
        ),
    "ropper":     ToolSpec(
            name="ropper",
            binary="ropper",
            description="Show ROP gadgets and search in binaries",
            params={"file": None},
            timeout=120,
            risk_level="passive",
            category="binary",
            builder=lambda p: ["ropper", "--file", p["file"], "--nocolor"],
        ),
}
