"""Cloud security (AWS/Azure/GCP) tool specs."""

from .._spec import ToolSpec


TOOLS = {
    "aws_get_caller_identity":     ToolSpec(
            name="aws_get_caller_identity",
            binary="aws",
            description="Show the current AWS identity (read-only)",
            params={},
            timeout=60,
            risk_level="passive",
            category="cloud",
            builder=lambda p: ["aws", "sts", "get-caller-identity", "--output", "json"],
        ),
    "aws_list_s3_buckets":     ToolSpec(
            name="aws_list_s3_buckets",
            binary="aws",
            description="List S3 buckets (read-only)",
            params={},
            timeout=60,
            risk_level="passive",
            category="cloud",
            builder=lambda p: ["aws", "s3api", "list-buckets", "--output", "json"],
        ),
    "aws_get_bucket_acl":     ToolSpec(
            name="aws_get_bucket_acl",
            binary="aws",
            description="Read one S3 bucket's ACL (read-only)",
            params={"bucket": None},
            timeout=60,
            risk_level="passive",
            category="cloud",
            builder=lambda p: ["aws", "s3api", "get-bucket-acl", "--bucket", p["bucket"], "--output", "json"],
        ),
    "aws_list_iam_users":     ToolSpec(
            name="aws_list_iam_users",
            binary="aws",
            description="List IAM users (read-only)",
            params={},
            timeout=60,
            risk_level="passive",
            category="cloud",
            builder=lambda p: ["aws", "iam", "list-users", "--output", "json"],
        ),
    "gcloud_list_projects":     ToolSpec(
            name="gcloud_list_projects",
            binary="gcloud",
            description="List GCP projects (read-only)",
            params={},
            timeout=60,
            risk_level="passive",
            category="cloud",
            builder=lambda p: ["gcloud", "projects", "list", "--format", "json"],
        ),
    "gcloud_list_instances":     ToolSpec(
            name="gcloud_list_instances",
            binary="gcloud",
            description="List Compute Engine instances (read-only)",
            params={},
            timeout=60,
            risk_level="passive",
            category="cloud",
            builder=lambda p: ["gcloud", "compute", "instances", "list", "--format", "json"],
        ),
    "az_account_show":     ToolSpec(
            name="az_account_show",
            binary="az",
            description="Show the current Azure account (read-only)",
            params={},
            timeout=30,
            risk_level="passive",
            category="cloud",
            builder=lambda p: ["az", "account", "show", "--output", "json"],
        ),
    "az_list_resource_groups":     ToolSpec(
            name="az_list_resource_groups",
            binary="az",
            description="List Azure resource groups (read-only)",
            params={},
            timeout=60,
            risk_level="passive",
            category="cloud",
            builder=lambda p: ["az", "group", "list", "--output", "json"],
        ),
    "prowler":     ToolSpec(
            name="prowler",
            binary="prowler",
            description="AWS security assessment with compliance checks",
            params={"profile": ""},
            timeout=1200,
            builder=lambda p: ["prowler", "aws"] + (["-p", p["profile"]] if p["profile"] else []) + ["--quiet"],
        ),
    "scoutsuite":     ToolSpec(
            name="scoutsuite",
            binary="scout",
            description="Multi-cloud security auditing",
            params={"provider": "aws"},
            timeout=1200,
            builder=lambda p: ["scout", p["provider"]],
        ),
    "aws_list_ec2":     ToolSpec(
            name="aws_list_ec2",
            binary="aws",
            description="List EC2 instances",
            params={},
            timeout=60,
            builder=lambda p: ["aws", "ec2", "describe-instances", "--output", "json"],
        ),
    "azure_account_list":     ToolSpec(
            name="azure_account_list",
            binary="az",
            description="List Azure subscriptions",
            params={},
            timeout=60,
            builder=lambda p: ["az", "account", "list", "--output", "json"],
        ),
    "terrascan":     ToolSpec(
            name="terrascan",
            binary="terrascan",
            description="IaC security scanning for Terraform, K8s, Helm, Dockerfiles",
            params={"path": "."},
            timeout=300,
            category="cloud",
            builder=lambda p: ["terrascan", "scan", "-d", p["path"], "-o", "json"],
        ),
}
