"""Static code / secret / dependency scanning tool specs."""

from .._spec import ToolSpec


TOOLS = {
    "semgrep":     ToolSpec(
            name="semgrep",
            binary="semgrep",
            description="Static analysis for multiple languages",
            params={"path": "."},
            timeout=300,
            builder=lambda p: ["semgrep", "--json", p["path"]],
        ),
    "sonarqube":     ToolSpec(
            name="sonarqube",
            binary="sonar-scanner",
            description="Code quality and security scanner",
            params={"project": None},
            timeout=600,
            builder=lambda p: ["sonar-scanner", "-Dsonar.projectKey=" + p["project"]],
        ),
    "pylint":     ToolSpec(
            name="pylint",
            binary="pylint",
            description="Python code analyzer",
            params={"file": None},
            timeout=60,
            builder=lambda p: ["pylint", p["file"]],
        ),
    "checkmarx":     ToolSpec(
            name="checkmarx",
            binary="checkmarx",
            description="Code security scanner",
            params={"path": "."},
            timeout=600,
            builder=lambda p: ["checkmarx", p["path"]],
        ),
    "npm_audit":     ToolSpec(
            name="npm_audit",
            binary="npm",
            description="NPM dependency vulnerability audit",
            params={"path": "."},
            timeout=60,
            builder=lambda p: ["npm", "audit", "--json"],
        ),
    "safety":     ToolSpec(
            name="safety",
            binary="safety",
            description="Python security vulnerability scanner",
            params={"file": "requirements.txt"},
            timeout=30,
            builder=lambda p: ["safety", "check", "-r", p["file"]],
        ),
    "snyk_test":     ToolSpec(
            name="snyk_test",
            binary="snyk",
            description="Scan a project's dependencies for known vulnerabilities",
            params={"path": "."},
            timeout=120,
            risk_level="passive",
            category="code",
            builder=lambda p: ["snyk", "test", "--json", f"--file={p['path']}"],
        ),
    "owasp_dependency_check":     ToolSpec(
            name="owasp_dependency_check",
            binary="dependency-check",
            description="OWASP dependency analyzer",
            params={"path": "."},
            timeout=300,
            builder=lambda p: ["dependency-check", "-scan", p["path"]],
        ),
    "trufflehog":     ToolSpec(
            name="trufflehog",
            binary="truffleHog",
            description="Detect secrets in git history",
            params={"repo": None},
            timeout=300,
            builder=lambda p: ["truffleHog", "git", p["repo"]],
        ),
    "gitrob":     ToolSpec(
            name="gitrob",
            binary="gitrob",
            description="GitHub reconnaissance tool",
            params={"user": None},
            timeout=120,
            builder=lambda p: ["gitrob", "scan", p["user"]],
        ),
    "tfsec":     ToolSpec(
            name="tfsec",
            binary="tfsec",
            description="Terraform security scanner",
            params={"path": "."},
            timeout=60,
            builder=lambda p: ["tfsec", p["path"]],
        ),
    "checkov":     ToolSpec(
            name="checkov",
            binary="checkov",
            description="Infrastructure as Code scanner",
            params={"path": "."},
            timeout=300,
            builder=lambda p: ["checkov", "-d", p["path"]],
        ),
    "bandit":     ToolSpec(
            name="bandit",
            binary="bandit",
            description="Python security linter",
            params={"path": None},
            timeout=300,
            builder=lambda p: ["bandit", "-r", p["path"], "-f", "json"],
        ),
    "detect_secrets":     ToolSpec(
            name="detect_secrets",
            binary="detect-secrets",
            description="Secret scanning for git repos",
            params={"path": None},
            timeout=120,
            builder=lambda p: ["detect-secrets", "scan", p["path"]],
        ),
    "pip_audit":     ToolSpec(
            name="pip_audit",
            binary="pip-audit",
            description="Python dependency vulnerability audit",
            params={"path": "requirements.txt"},
            timeout=300,
            builder=lambda p: ["pip-audit", "-r", p["path"], "-f", "json"],
        ),
    "osv_scanner":     ToolSpec(
            name="osv_scanner",
            binary="osv-scanner",
            description="OSV vulnerability scanner for dependency manifests",
            params={"path": None},
            timeout=300,
            builder=lambda p: ["osv-scanner", "-r", p["path"]],
        ),
}
