"""Container & Kubernetes security tool specs."""

from .._spec import ToolSpec


TOOLS = {
    "docker_list_containers":     ToolSpec(
            name="docker_list_containers",
            binary="docker",
            description="List Docker containers (read-only)",
            params={"all": ""},
            timeout=30,
            risk_level="passive",
            category="container",
            builder=lambda p: ["docker", "ps", "--format", "json"] + (["--all"] if p["all"] else []),
        ),
    "docker_inspect_container":     ToolSpec(
            name="docker_inspect_container",
            binary="docker",
            description="Inspect one Docker container (read-only)",
            params={"container": None},
            timeout=30,
            risk_level="passive",
            category="container",
            builder=lambda p: ["docker", "inspect", p["container"]],
        ),
    "docker_list_images":     ToolSpec(
            name="docker_list_images",
            binary="docker",
            description="List local Docker images (read-only)",
            params={},
            timeout=30,
            risk_level="passive",
            category="container",
            builder=lambda p: ["docker", "images", "--format", "json"],
        ),
    "kubectl_get_namespaces":     ToolSpec(
            name="kubectl_get_namespaces",
            binary="kubectl",
            description="List Kubernetes namespaces (read-only)",
            params={},
            timeout=30,
            risk_level="passive",
            category="container",
            builder=lambda p: ["kubectl", "get", "namespaces", "-o", "json"],
        ),
    "kubectl_get_pods":     ToolSpec(
            name="kubectl_get_pods",
            binary="kubectl",
            description="List pods in a namespace (read-only)",
            params={"namespace": "default"},
            timeout=30,
            risk_level="passive",
            category="container",
            builder=lambda p: ["kubectl", "get", "pods", "-n", p["namespace"], "-o", "json"],
        ),
    "kubectl_get_nodes":     ToolSpec(
            name="kubectl_get_nodes",
            binary="kubectl",
            description="List cluster nodes (read-only)",
            params={},
            timeout=30,
            risk_level="passive",
            category="container",
            builder=lambda p: ["kubectl", "get", "nodes", "-o", "json"],
        ),
    "trivy":     ToolSpec(
            name="trivy",
            binary="trivy",
            description="Container vulnerability scanner",
            params={"image": None},
            timeout=300,
            builder=lambda p: ["trivy", "image", p["image"]],
        ),
    "grype":     ToolSpec(
            name="grype",
            binary="grype",
            description="Vulnerability scanner for containers",
            params={"image": None},
            timeout=300,
            builder=lambda p: ["grype", p["image"]],
        ),
    "kube_bench":     ToolSpec(
            name="kube_bench",
            binary="kube-bench",
            description="Kubernetes security audit",
            params={},
            timeout=120,
            builder=lambda p: ["kube-bench", "run"],
        ),
    "kube_hunter":     ToolSpec(
            name="kube_hunter",
            binary="kube-hunter",
            description="Kubernetes penetration testing",
            params={"pod": "default"},
            timeout=300,
            builder=lambda p: ["kube-hunter", "--pod", p["pod"]],
        ),
    "falco":     ToolSpec(
            name="falco",
            binary="falco",
            description="Runtime security monitoring",
            params={},
            timeout=60,
            builder=lambda p: ["falco", "-o", "json_output=true"],
        ),
    "kubectl_get_services":     ToolSpec(
            name="kubectl_get_services",
            binary="kubectl",
            description="List Kubernetes services",
            params={},
            timeout=60,
            builder=lambda p: ["kubectl", "get", "services", "-o", "wide"],
        ),
    "kubectl_get_deployments":     ToolSpec(
            name="kubectl_get_deployments",
            binary="kubectl",
            description="List Kubernetes deployments",
            params={},
            timeout=60,
            builder=lambda p: ["kubectl", "get", "deployments", "-o", "wide"],
        ),
    "docker_network_ls":     ToolSpec(
            name="docker_network_ls",
            binary="docker",
            description="List Docker networks",
            params={},
            timeout=60,
            builder=lambda p: ["docker", "network", "ls"],
        ),
}
