"""Digital forensics tool specs."""

from .._spec import ToolSpec


TOOLS = {
    "exiftool":     ToolSpec(
            name="exiftool",
            binary="exiftool",
            description="Extract metadata from files",
            params={"file": None},
            timeout=30,
            builder=lambda p: ["exiftool", p["file"]],
        ),
    "binwalk":     ToolSpec(
            name="binwalk",
            binary="binwalk",
            description="Firmware analysis and extraction",
            params={"file": None},
            timeout=60,
            builder=lambda p: ["binwalk", p["file"]],
        ),
    "foremost":     ToolSpec(
            name="foremost",
            binary="foremost",
            description="File carving and recovery",
            params={"file": None},
            timeout=300,
            builder=lambda p: ["foremost", p["file"]],
        ),
    "metadata_anonymizer":     ToolSpec(
            name="metadata_anonymizer",
            binary="exiftool",
            description="Remove metadata",
            params={"file": None},
            timeout=30,
            builder=lambda p: ["exiftool", "-All=", p["file"]],
        ),
    "volatility":     ToolSpec(
            name="volatility",
            binary="volatility",
            description="Memory forensics framework",
            params={"dump": None},
            timeout=300,
            builder=lambda p: ["volatility", "-f", p["dump"], "imageinfo"],
        ),
    "sleuthkit":     ToolSpec(
            name="sleuthkit",
            binary="fls",
            description="Filesystem analysis",
            params={"image": None},
            timeout=300,
            builder=lambda p: ["fls", p["image"]],
        ),
    "autopsy":     ToolSpec(
            name="autopsy",
            binary="autopsy",
            description="Digital forensics platform",
            params={"image": None},
            timeout=600,
            builder=lambda p: ["autopsy", p["image"]],
        ),
    "regripper":     ToolSpec(
            name="regripper",
            binary="rip.pl",
            description="Windows registry extraction",
            params={"hive": None},
            timeout=60,
            builder=lambda p: ["rip.pl", "-r", p["hive"]],
        ),
    "steghide":     ToolSpec(
            name="steghide",
            binary="steghide",
            description="Inspect or extract data hidden in media files",
            params={"file": None, "extract": False},
            timeout=60,
            risk_level="passive",
            builder=lambda p: (
                ["steghide", "extract", "-sf", p["file"], "-p", ""] if p["extract"] else ["steghide", "info", p["file"]]
            ),
        ),
    "zsteg":     ToolSpec(
            name="zsteg",
            binary="zsteg",
            description="Detect hidden data in PNG/BMP files",
            params={"file": None},
            timeout=60,
            risk_level="passive",
            builder=lambda p: ["zsteg", p["file"]],
        ),
    "pngcheck":     ToolSpec(
            name="pngcheck",
            binary="pngcheck",
            description="Verify and analyze PNG file integrity",
            params={"file": None},
            timeout=30,
            risk_level="passive",
            builder=lambda p: ["pngcheck", "-v", p["file"]],
        ),
    "fcrackzip":     ToolSpec(
            name="fcrackzip",
            binary="fcrackzip",
            description="Dictionary attack on password-protected ZIP files",
            params={"file": None, "wordlist": "/usr/share/wordlists/rockyou.txt"},
            timeout=300,
            builder=lambda p: ["fcrackzip", "-u", "-D", "-p", p["wordlist"], p["file"]],
        ),
    "bulk_extractor":     ToolSpec(
            name="bulk_extractor",
            binary="bulk_extractor",
            description="Digital forensics feature extraction",
            params={"image": None},
            timeout=600,
            builder=lambda p: ["bulk_extractor", "-o", "bulk_extractor_out", p["image"]],
        ),
    "pdf2txt":     ToolSpec(
            name="pdf2txt",
            binary="pdf2txt.py",
            description="Extract text from PDF files",
            params={"file": None},
            timeout=120,
            builder=lambda p: ["pdf2txt.py", p["file"]],
        ),
}
