"""Network protocol tools tool specs."""

from .._spec import ToolSpec


TOOLS = {
    "arp_scan":     ToolSpec(
                name="arp_scan",
                binary="arp-scan",
                description="ARP scanner",
                params={"interface": None},
                timeout=60,
                builder=lambda p: ["arp-scan", "-l", "-I", p["interface"]] if p["interface"] else ["arp-scan", "-l"],
            ),
    "tcpdump":     ToolSpec(
                name="tcpdump",
                binary="tcpdump",
                description="Packet sniffer",
                params={"interface": "any"},
                timeout=30,
                cacheable=False,
                builder=lambda p: ["tcpdump", "-i", p["interface"], "-n", "-l"],
            ),
    "tshark":     ToolSpec(
                name="tshark",
                binary="tshark",
                description="Wireshark command-line packet analyzer",
                params={"interface": "any"},
                timeout=30,
                cacheable=False,
                builder=lambda p: ["tshark", "-i", p["interface"]],
            ),
    "enum4linux":     ToolSpec(
                name="enum4linux",
                binary="enum4linux",
                description="SMB/CIFS enumeration",
                params={"target": None},
                timeout=120,
                builder=lambda p: ["enum4linux", "-a", p["target"]],
            ),
    "smbmap":     ToolSpec(
                name="smbmap",
                binary="smbmap",
                description="SMB share enumeration",
                params={"host": None},
                timeout=60,
                builder=lambda p: ["smbmap", "-H", p["host"]],
            ),
    "smbclient":     ToolSpec(
                name="smbclient",
                binary="smbclient",
                description="SMB client",
                params={"path": None},
                timeout=30,
                builder=lambda p: ["smbclient", p["path"]],
            ),
    "rpcclient":     ToolSpec(
                name="rpcclient",
                binary="rpcclient",
                description="RPC client",
                params={"server": None},
                timeout=30,
                builder=lambda p: ["rpcclient", p["server"]],
            ),
    "ldapsearch":     ToolSpec(
                name="ldapsearch",
                binary="ldapsearch",
                description="LDAP search",
                params={"server": None},
                timeout=30,
                builder=lambda p: ["ldapsearch", "-H", f"ldap://{p['server']}", "-x"],
            ),
    "tun2socks":     ToolSpec(
                name="tun2socks",
                binary="tun2socks",
                description="TUN tunnel",
                params={"socks": "127.0.0.1:1080"},
                timeout=300,
                builder=lambda p: ["tun2socks", "--socks", p["socks"]],
            ),
    "wireshark":     ToolSpec(
                name="wireshark",
                binary="wireshark",
                description="Network protocol analyzer",
                params={"pcap": None},
                timeout=60,
                builder=lambda p: ["wireshark", "-r", p["pcap"]],
            ),
    "netdiscover":     ToolSpec(
                name="netdiscover",
                binary="netdiscover",
                description="ARP-based live host discovery on a subnet",
                params={"range": None},
                timeout=120,
                builder=lambda p: ["netdiscover", "-r", p["range"]],
            ),
    "responder":     ToolSpec(
                name="responder",
                binary="responder",
                description="LLMNR/NBT-NS/mDNS poisoning and credential recovery",
                params={"interface": None, "mode": "off"},
                timeout=300,
                risk_level="intrusive",
                builder=lambda p: ["responder", "-I", p["interface"], "-v"] + (["-A"] if p["mode"] == "analyze" else []),
            ),
    "snmpwalk":     ToolSpec(
                name="snmpwalk",
                binary="snmpwalk",
                description="Enumerate SNMP MIB tree of a target",
                params={"host": None, "community": "public"},
                timeout=120,
                builder=lambda p: ["snmpwalk", "-c", p["community"], "-v2c", p["host"]],
            ),
    "nbtscan":     ToolSpec(
                name="nbtscan",
                binary="nbtscan",
                description="NetBIOS name service scanner over a subnet",
                params={"range": None},
                timeout=120,
                category="network",
                builder=lambda p: ["nbtscan", "-f", p["range"]],
            ),
    "mitm6":     ToolSpec(
                name="mitm6",
                binary="mitm6",
                description="IPv6 DNS takeover and WPAD poisoning for AD credential capture",
                params={"domain": None, "interface": None},
                timeout=300,
                risk_level="intrusive",
                category="network",
                builder=lambda p: ["mitm6", "-d", p["domain"], "-i", p["interface"]],
            ),
    "bloodhound":     ToolSpec(
                name="bloodhound",
                binary="bloodhound-python",
                description="Active Directory mapping: users, groups, trusts, sessions",
                params={"domain": None, "user": None, "password": None, "nameserver": ""},
                timeout=600,
                risk_level="active",
                category="network",
                builder=lambda p: (
                    ["bloodhound-python", "-d", p["domain"], "-u", p["user"], "-p", p["password"]]
                    + (["-ns", p["nameserver"]] if p["nameserver"] else [])
                ),
            ),
    "tcpdump_capture":     ToolSpec(
                name="tcpdump_capture",
                binary="tcpdump",
                description="Live packet capture",
                params={"interface": "any", "count": 100, "port": ""},
                timeout=120,
                cacheable=False,
                # A tcpdump filter expression ("port 80") must come last, after the
                # options; -w is an option, so the filter follows it.
                builder=lambda p: (
                    ["tcpdump", "-i", p["interface"], "-c", str(p["count"]), "-w", "capture.pcap"]
                    + (["port", str(p["port"])] if p["port"] else [])
                ),
            ),
    "tshark_capture":     ToolSpec(
                name="tshark_capture",
                binary="tshark",
                description="Live packet analysis",
                params={"interface": "any", "count": 100},
                timeout=120,
                cacheable=False,
                builder=lambda p: ["tshark", "-i", p["interface"], "-c", str(p["count"])],
            ),
    "enum4linux_ng":     ToolSpec(
                name="enum4linux_ng",
                binary="enum4linux-ng",
                description="SMB enumeration with user/group/share discovery",
                params={"host": None},
                timeout=300,
                builder=lambda p: ["enum4linux-ng", "-A", p["host"]],
            ),
    "snmp_check":     ToolSpec(
                name="snmp_check",
                binary="snmp-check",
                description="SNMP enumeration",
                params={"host": None},
                timeout=120,
                builder=lambda p: ["snmp-check", p["host"]],
            ),
    "impacket_psexec":     ToolSpec(
                name="impacket_psexec",
                binary="psexec.py",
                description="Remote execution via SMB (impacket)",
                params={"host": None, "user": None, "password": "", "domain": ""},
                timeout=600,
                builder=lambda p: ["psexec.py", f"{p['domain']}/{p['user']}:{p['password']}@{p['host']}"],
            ),
}
