"""OSINT tool specs."""

from .._spec import ToolSpec


TOOLS = {
    "searchsploit":     ToolSpec(
            name="searchsploit",
            binary="searchsploit",
            description="Search the local ExploitDB database",
            params={"query": None},
            timeout=30,
            risk_level="passive",
            builder=lambda p: ["searchsploit", p["query"]],
        ),
    "cve_search":     ToolSpec(
            name="cve_search",
            binary="cve_search",
            description="Search CVE database",
            params={"query": None},
            timeout=30,
            risk_level="passive",
            builder=lambda p: ["cve_search", p["query"]],
        ),
    "zoomeye":     ToolSpec(
            name="zoomeye",
            binary="zoomeye",
            description="ZoomEye CLI",
            params={"query": None},
            timeout=30,
            builder=lambda p: ["zoomeye", p["query"]],
        ),
    "nist_tool":     ToolSpec(
            name="nist_tool",
            binary="nist-scan",
            description="NIST compliance checker",
            params={"target": None},
            timeout=300,
            risk_level="passive",
            builder=lambda p: ["nist-scan", p["target"]],
        ),
    "maltego":     ToolSpec(
            name="maltego",
            binary="maltego",
            description="OSINT data mining and visualization",
            params={"entity": None},
            timeout=120,
            builder=lambda p: ["maltego", p["entity"]],
        ),
    "spiderfoot":     ToolSpec(
            name="spiderfoot",
            binary="spiderfoot",
            description="OSINT automation framework",
            params={"target": None},
            timeout=300,
            builder=lambda p: ["spiderfoot", "-s", p["target"]],
        ),
    "sherlock":     ToolSpec(
            name="sherlock",
            binary="sherlock",
            description="Username enumeration across social networks",
            params={"username": None},
            timeout=60,
            risk_level="passive",
            builder=lambda p: ["sherlock", p["username"]],
        ),
    "holehe":     ToolSpec(
            name="holehe",
            binary="holehe",
            description="Check if an email is registered on online services",
            params={"email": None},
            timeout=60,
            risk_level="passive",
            builder=lambda p: ["holehe", p["email"]],
        ),
    "maigret":     ToolSpec(
            name="maigret",
            binary="maigret",
            description="Username footprinting across hundreds of sites",
            params={"username": None, "limit": "100"},
            timeout=300,
            risk_level="passive",
            builder=lambda p: ["maigret", "--no-recursion", "--limit", str(p["limit"]), p["username"]],
        ),
    "phoneinfoga":     ToolSpec(
            name="phoneinfoga",
            binary="phoneinfoga",
            description="Phone number OSINT and carrier intelligence",
            params={"number": None},
            timeout=60,
            risk_level="passive",
            builder=lambda p: ["phoneinfoga", "scan", "-n", p["number"]],
        ),
}
