"""Reconnaissance & discovery tool specs."""

from .._spec import ToolSpec
from .._builders import _build_nmap_advanced, _build_masscan_advanced
from nexhunter.core import params as P


TOOLS = {
    "nmap_scan":     ToolSpec(
            name="nmap_scan",
            binary="nmap",
            description="Port/service discovery",
            params={"target": None, "ports": "", "timing": "4"},
            timeout=300,
            parser="nmap_xml",
            builder=lambda p: (
                ["nmap", "-sV", f"-T{p['timing']}", "-oX", "-"] + (["-p", p["ports"]] if p["ports"] else []) + [p["target"]]
            ),
        ),
    "nmap_advanced_scan":     ToolSpec(
            name="nmap_advanced_scan",
            binary="nmap",
            description="Nmap with fine control: OS detection, version detection, "
            "aggressive, stealth, NSE scripts, and timing",
            params={
                "target": None,
                "ports": "",
                "timing": "4",
                "os_detection": False,
                "version_detection": True,
                "aggressive": False,
                "stealth": False,
                "nse_scripts": "",
            },
            timeout=600,
            param_specs=(
                P.ParamSpec(name="target", type=P.ParamType.TARGET, required=True),
                P.ParamSpec(name="ports", type=P.ParamType.PORT_RANGE, default=""),
                P.ParamSpec(name="timing", type=P.ParamType.STRING, default="4"),
                P.ParamSpec(name="os_detection", type=P.ParamType.BOOLEAN, default=False),
                P.ParamSpec(name="version_detection", type=P.ParamType.BOOLEAN, default=True),
                P.ParamSpec(name="aggressive", type=P.ParamType.BOOLEAN, default=False),
                P.ParamSpec(name="stealth", type=P.ParamType.BOOLEAN, default=False),
                P.ParamSpec(name="nse_scripts", type=P.ParamType.STRING, default=""),
            ),
            builder=_build_nmap_advanced,
            category="recon",
            risk_level="active",
            maturity="beta",
            cacheable=True,
            parser="nmap_xml",
        ),
    "masscan":     ToolSpec(
            name="masscan",
            binary="masscan",
            description="Fast port scanner",
            params={"target": None, "ports": "1-65535", "rate": 1000},
            timeout=600,
            builder=lambda p: ["masscan", p["target"], "-p", p["ports"], "-oG", "-", "--rate", str(p["rate"])],
            category="recon",
            risk_level="active",
            parser="masscan_grep",
        ),
    "masscan_advanced_scan":     ToolSpec(
            name="masscan_advanced_scan",
            binary="masscan",
            description="Masscan with rate control and thread tuning",
            params={"target": None, "ports": "1-65535", "rate": 1000, "threads": ""},
            timeout=600,
            param_specs=(
                P.ParamSpec(name="target", type=P.ParamType.TARGET, required=True),
                P.ParamSpec(name="ports", type=P.ParamType.PORT_RANGE, default="1-65535"),
                P.ParamSpec(name="rate", type=P.ParamType.INTEGER, default=1000, minimum=1),
                P.ParamSpec(name="threads", type=P.ParamType.INTEGER, default=None),
            ),
            builder=_build_masscan_advanced,
            category="recon",
            risk_level="active",
            maturity="beta",
            cacheable=True,
            parser="masscan_grep",
        ),
    "rustscan":     ToolSpec(
            name="rustscan",
            binary="rustscan",
            description="Fast port scanner in Rust",
            params={"target": None},
            timeout=300,
            builder=lambda p: ["rustscan", "-a", p["target"], "--", "-sV", "-T4"],
        ),
    "subfinder_enum":     ToolSpec(
            name="subfinder_enum",
            binary="subfinder",
            description="Passive subdomain enumeration",
            params={"domain": None},
            timeout=60,
            parser="hosts",
            builder=lambda p: ["subfinder", "-d", p["domain"], "-silent"],
        ),
    "amass_enum":     ToolSpec(
            name="amass_enum",
            binary="amass",
            description="Passive subdomain enumeration",
            params={"domain": None},
            timeout=120,
            parser="hosts",
            builder=lambda p: ["amass", "enum", "-passive", "-d", p["domain"]],
        ),
    "assetfinder":     ToolSpec(
            name="assetfinder",
            binary="assetfinder",
            description="Find subdomains from certificate transparency",
            params={"domain": None},
            timeout=60,
            parser="hosts",
            builder=lambda p: ["assetfinder", p["domain"]],
        ),
    "dns_lookup":     ToolSpec(
            name="dns_lookup",
            binary="dig",
            description="DNS query/enumeration",
            params={"domain": None, "type": "A"},
            timeout=15,
            builder=lambda p: ["dig", "+short", p["domain"], p["type"]],
        ),
    "nslookup":     ToolSpec(
            name="nslookup",
            binary="nslookup",
            description="DNS lookup",
            params={"domain": None},
            timeout=15,
            builder=lambda p: ["nslookup", p["domain"]],
        ),
    "whois_lookup":     ToolSpec(
            name="whois_lookup",
            binary="whois",
            description="WHOIS lookup",
            params={"query": None},
            timeout=30,
            builder=lambda p: ["whois", p["query"]],
        ),
    "host_lookup":     ToolSpec(
            name="host_lookup",
            binary="host",
            description="DNS hostname lookup",
            params={"host": None},
            timeout=15,
            builder=lambda p: ["host", p["host"]],
        ),
    "subfinder":     ToolSpec(
            name="subfinder",
            binary="subfinder",
            description="Subdomain finder",
            params={"domain": None},
            timeout=60,
            builder=lambda p: ["subfinder", "-d", p["domain"], "-silent"],
        ),
    "shodan":     ToolSpec(
            name="shodan",
            binary="shodan",
            description="Shodan search engine CLI",
            params={"query": None},
            timeout=30,
            builder=lambda p: ["shodan", "search", p["query"]],
        ),
    "censys":     ToolSpec(
            name="censys",
            binary="censys-cli",
            description="Censys.io CLI",
            params={"query": None},
            timeout=30,
            builder=lambda p: ["censys-cli", "search", p["query"]],
        ),
    "dnscat2":     ToolSpec(
            name="dnscat2",
            binary="dnscat2",
            description="DNS exfiltration",
            params={"domain": None},
            timeout=300,
            builder=lambda p: ["dnscat2", p["domain"]],
        ),
    "shodan_host_lookup":     ToolSpec(
            name="shodan_host_lookup",
            binary="shodan",
            description="Look up a host in Shodan (passive, no traffic to the target)",
            params={"ip": None},
            timeout=30,
            risk_level="passive",
            category="recon",
            builder=lambda p: ["shodan", "host", p["ip"]],
        ),
    "theharvester_recon":     ToolSpec(
            name="theharvester_recon",
            binary="theHarvester",
            description="OSINT email and host harvesting",
            params={"domain": None, "limit": "100"},
            timeout=120,
            risk_level="passive",
            builder=lambda p: ["theHarvester", "-d", p["domain"], "-b", "all", "-l", str(p["limit"])],
        ),
    "dnsx":     ToolSpec(
            name="dnsx",
            binary="dnsx",
            description="DNS resolver and probe",
            params={"domain": None},
            timeout=60,
            parser="dnsx_resp",
            builder=lambda p: ["dnsx", "-d", p["domain"], "-a", "-resp", "-silent"],
        ),
    "naabu":     ToolSpec(
            name="naabu",
            binary="naabu",
            description="Fast port scanner",
            params={"host": None, "rate": 1000},
            timeout=300,
            parser="host_port",
            builder=lambda p: ["naabu", "-host", p["host"], "-silent", "-rate", str(p["rate"])],
        ),
    "dig_axfr":     ToolSpec(
            name="dig_axfr",
            binary="dig",
            description="DNS zone transfer attempt",
            params={"domain": None},
            timeout=30,
            builder=lambda p: ["dig", "AXFR", p["domain"], "+short"],
        ),
    "theharvester":     ToolSpec(
            name="theharvester",
            binary="theharvester",
            description="Email and subdomain harvesting",
            params={"domain": None},
            timeout=300,
            builder=lambda p: ["theharvester", "-d", p["domain"], "-b", "all"],
        ),
    "shodan_search":     ToolSpec(
            name="shodan_search",
            binary="shodan",
            description="Shodan device search",
            params={"query": None},
            timeout=60,
            builder=lambda p: ["shodan", "search", p["query"]],
        ),
    "censys_search":     ToolSpec(
            name="censys_search",
            binary="censys",
            description="Censys asset search",
            params={"query": None},
            timeout=60,
            builder=lambda p: ["censys", "search", p["query"]],
        ),
    "dnsrecon":     ToolSpec(
            name="dnsrecon",
            binary="dnsrecon",
            description="DNS reconnaissance and zone enumeration",
            params={"domain": None},
            timeout=300,
            builder=lambda p: ["dnsrecon", "-d", p["domain"], "-t", "std", "-j", "dnsrecon.json"],
        ),
    "fping":     ToolSpec(
            name="fping",
            binary="fping",
            description="Fast ICMP host discovery across a subnet",
            params={"subnet": None},
            timeout=120,
            builder=lambda p: ["fping", "-a", "-g", p["subnet"]],
        ),
    "autorecon":     ToolSpec(
            name="autorecon",
            binary="autorecon",
            description="Multi-phase automated recon: ports, services, vulns, web",
            params={"target": None},
            timeout=1200,
            risk_level="active",
            builder=lambda p: ["autorecon", p["target"], "--single-target", "-o", "autorecon_out"],
        ),
    "fierce":     ToolSpec(
            name="fierce",
            binary="fierce",
            description="DNS enumeration: locate non-contiguous IP space and subdomains",
            params={"domain": None},
            timeout=300,
            builder=lambda p: ["fierce", "--domain", p["domain"]],
        ),
    "dnsenum":     ToolSpec(
            name="dnsenum",
            binary="dnsenum",
            description="DNS zone enumeration: records, subdomains, zone transfer, bruteforce",
            params={"domain": None},
            timeout=300,
            builder=lambda p: ["dnsenum", "--enum", p["domain"]],
        ),
}
