"""Web application security tool specs."""

import shlex

from .._spec import ToolSpec, ShellCommand, browser_engine_available
from .._builders import _build_ffuf_advanced
from nexhunter.core import params as P


TOOLS = {
    "nuclei_scan":     ToolSpec(
            name="nuclei_scan",
            binary="nuclei",
            description="Vulnerability scanner with templates",
            params={"target": None, "severity": ""},
            timeout=300,
            parser="nuclei",
            builder=lambda p: (
                ["nuclei", "-u", p["target"], "-silent", "-jsonl"] + (["-severity", p["severity"]] if p["severity"] else [])
            ),
        ),
    "ffuf_scan":     ToolSpec(
            name="ffuf_scan",
            binary="ffuf",
            description="Web content fuzzer",
            params={"target": None, "wordlist": None, "filter_status": "", "threads": 40},
            timeout=300,
            parser="ffuf",
            builder=lambda p: (
                ["ffuf", "-u", p["target"].rstrip("/") + "/FUZZ", "-w", p["wordlist"], "-t", str(p["threads"])]
                + (["-fs", p["filter_status"]] if p["filter_status"] else [])
            ),
        ),
    "ffuf_advanced_scan":     ToolSpec(
            name="ffuf_advanced_scan",
            binary="ffuf",
            description="Ffuf with multiple keyword wordlists (comma-separated), method, and matcher/filter status",
            params={
                "target": None,
                "wordlists": None,
                "threads": 40,
                "method": "",
                "filter_status": "",
                "matcher_status": "",
            },
            timeout=600,
            param_specs=(
                P.ParamSpec(name="target", type=P.ParamType.URL, required=True),
                P.ParamSpec(name="wordlists", type=P.ParamType.STRING, required=True),
                P.ParamSpec(name="threads", type=P.ParamType.INTEGER, default=40, minimum=1),
                P.ParamSpec(name="method", type=P.ParamType.STRING, default=""),
                P.ParamSpec(name="filter_status", type=P.ParamType.STRING, default=""),
                P.ParamSpec(name="matcher_status", type=P.ParamType.STRING, default=""),
            ),
            builder=_build_ffuf_advanced,
            category="web",
            risk_level="active",
            maturity="beta",
            cacheable=True,
        ),
    "gobuster_dir":     ToolSpec(
            name="gobuster_dir",
            binary="gobuster",
            description="Directory brute force",
            params={"target": None, "wordlist": None, "extensions": "", "threads": 40},
            timeout=300,
            builder=lambda p: (
                ["gobuster", "dir", "-u", p["target"], "-w", p["wordlist"], "-t", str(p["threads"])]
                + (["-x", p["extensions"]] if p["extensions"] else [])
            ),
        ),
    "gobuster_dns":     ToolSpec(
            name="gobuster_dns",
            binary="gobuster",
            description="DNS subdomain brute force",
            params={"domain": None, "wordlist": None, "threads": 40},
            timeout=300,
            builder=lambda p: ["gobuster", "dns", "-d", p["domain"], "-w", p["wordlist"], "-t", str(p["threads"])],
        ),
    "nikto_scan":     ToolSpec(
            name="nikto_scan",
            binary="nikto",
            description="Web server vulnerability scan",
            params={"target": None},
            timeout=300,
            parser="nikto",
            builder=lambda p: ["nikto", "-h", p["target"]],
        ),
    "sqlmap_scan":     ToolSpec(
            name="sqlmap_scan",
            binary="sqlmap",
            description="SQL injection tester",
            params={"url": None},
            timeout=600,
            parser="sqlmap",
            builder=lambda p: ["sqlmap", "-u", p["url"], "--batch", "--random-agent"],
        ),
    "dalfox_xss":     ToolSpec(
            name="dalfox_xss",
            binary="dalfox",
            description="XSS vulnerability scanner",
            params={"url": None},
            timeout=300,
            builder=lambda p: ["dalfox", "url", p["url"]],
        ),
    "httpx_probe":     ToolSpec(
            name="httpx_probe",
            binary="httpx",
            description="HTTP probe with tech detection",
            params={"target": None},
            timeout=60,
            parser="httpx",
            builder=lambda p: ["httpx", "-u", p["target"], "-status-code", "-title", "-tech-detect", "-silent", "-json"],
        ),
    "curl_headers":     ToolSpec(
            name="curl_headers",
            binary="curl",
            description="Fetch HTTP headers",
            params={"url": None},
            timeout=30,
            builder=lambda p: ["curl", "-sSI", "--max-time", "15", p["url"]],
        ),
    "wpscan_scan":     ToolSpec(
            name="wpscan_scan",
            binary="wpscan",
            description="WordPress vulnerability scanner",
            params={"url": None, "api_token": ""},
            timeout=300,
            parser="wpscan",
            builder=lambda p: (
                ["wpscan", "--url", p["url"], "--random-user-agent"]
                + (["--api-token", p["api_token"]] if p["api_token"] else [])
            ),
        ),
    "joomscan":     ToolSpec(
            name="joomscan",
            binary="joomscan",
            description="Joomla vulnerability scanner",
            params={"url": None},
            timeout=300,
            builder=lambda p: ["joomscan", "--url", p["url"]],
        ),
    "drupscan":     ToolSpec(
            name="drupscan",
            binary="drupscan",
            description="Drupal vulnerability scanner",
            params={"url": None},
            timeout=300,
            builder=lambda p: ["drupscan", "scan", "--url", p["url"]],
        ),
    "commix":     ToolSpec(
            name="commix",
            binary="commix",
            description="Command injection tester",
            params={"url": None},
            timeout=300,
            builder=lambda p: ["commix", "-u", p["url"], "--batch"],
        ),
    "xsstrike":     ToolSpec(
            name="xsstrike",
            binary="xsstrike",
            description="XSS vulnerability tester",
            params={"url": None},
            timeout=300,
            builder=lambda p: ["xsstrike", "-u", p["url"]],
        ),
    "testssl":     ToolSpec(
            name="testssl",
            binary="testssl.sh",
            description="SSL/TLS vulnerability scanner",
            params={"url": None},
            timeout=300,
            category="web",
            parser="testssl",
            builder=lambda p: ["testssl.sh", p["url"]],
        ),
    "curl":     ToolSpec(
            name="curl",
            binary="curl",
            description="URL data transfer",
            params={"url": None},
            timeout=30,
            builder=lambda p: ["curl", "-v", p["url"]],
        ),
    "burpsuite":     ToolSpec(
            name="burpsuite",
            binary="burpsuite",
            description="Web security testing platform",
            params={"project": None},
            timeout=600,
            builder=lambda p: ["burpsuite", "--headless", "--project-file=" + p["project"]],
        ),
    "zap":     ToolSpec(
            name="zap",
            binary="zaproxy",
            description="OWASP ZAP web scanner",
            params={"url": None},
            timeout=600,
            builder=lambda p: ["zaproxy", "-cmd", "-quickurl", p["url"]],
        ),
    "rest_client":     ToolSpec(
            name="rest_client",
            binary="http",
            description="HTTPie HTTP client",
            params={"url": None},
            timeout=30,
            builder=lambda p: ["http", "GET", p["url"]],
        ),
    "nuclei_templates":     ToolSpec(
            name="nuclei_templates",
            binary="nuclei",
            description="Nuclei template lister",
            params={},
            timeout=30,
            builder=lambda p: ["nuclei", "-list-templates"],
        ),
    "wafw00f":     ToolSpec(
            name="wafw00f",
            binary="wafw00f",
            description="Detect Web Application Firewalls in front of a target",
            params={"url": None},
            timeout=60,
            risk_level="passive",
            builder=lambda p: ["wafw00f", p["url"]],
        ),
    "katana_crawl":     ToolSpec(
            name="katana_crawl",
            binary="katana",
            description="Web crawler with JS rendering",
            params={"url": None, "depth": 3},
            timeout=300,
            parser="urls",
            builder=lambda p: ["katana", "-u", p["url"], "-silent", "-jc", "-d", str(p["depth"])],
        ),
    "waybackurls":     ToolSpec(
            name="waybackurls",
            binary="waybackurls",
            description="Historical URLs from the Wayback Machine",
            params={"domain": None},
            timeout=60,
            parser="urls",
            builder=lambda p: ["waybackurls", p["domain"]],
        ),
    "gau":     ToolSpec(
            name="gau",
            binary="gau",
            description="Get all URLs from many archives",
            params={"domain": None},
            timeout=120,
            parser="urls",
            builder=lambda p: ["gau", p["domain"]],
        ),
    "paramspider":     ToolSpec(
            name="paramspider",
            binary="paramspider",
            description="Parameter mining from web archives",
            params={"domain": None},
            timeout=120,
            builder=lambda p: ["paramspider", "-d", p["domain"]],
        ),
    "whatweb_scan":     ToolSpec(
            name="whatweb_scan",
            binary="whatweb",
            description="Web technology identification",
            params={"url": None},
            timeout=60,
            parser="whatweb",
            builder=lambda p: ["whatweb", p["url"]],
        ),
    "feroxbuster":     ToolSpec(
            name="feroxbuster",
            binary="feroxbuster",
            description="Recursive content discovery",
            params={"url": None, "wordlist": None, "extensions": "", "threads": 40},
            timeout=600,
            parser="urls",
            builder=lambda p: (
                ["feroxbuster", "-u", p["url"], "-w", p["wordlist"], "-q", "-t", str(p["threads"])]
                + (["-x", p["extensions"]] if p["extensions"] else [])
            ),
        ),
    "dirsearch":     ToolSpec(
            name="dirsearch",
            binary="dirsearch",
            description="Directory/file discovery",
            params={"url": None, "extensions": "php,asp,aspx,jsp,html,js", "threads": 40},
            timeout=300,
            builder=lambda p: [
                "dirsearch",
                "-u",
                p["url"],
                "-e",
                p["extensions"],
                "--format",
                "plain",
                "-t",
                str(p["threads"]),
            ],
        ),
    "linkfinder":     ToolSpec(
            name="linkfinder",
            binary="linkfinder.py",
            description="Extract endpoints from JavaScript files",
            params={"url": None},
            timeout=60,
            builder=lambda p: ["linkfinder.py", "-d", p["url"], "-o", "linkfinder.html"],
        ),
    "corsy":     ToolSpec(
            name="corsy",
            binary="corsy",
            description="CORS misconfiguration scanner",
            params={"url": None},
            timeout=120,
            builder=lambda p: ["corsy", "-u", p["url"]],
        ),
    "subjack":     ToolSpec(
            name="subjack",
            binary="subjack",
            description="Subdomain takeover checker",
            params={"wordlist": None, "threads": 10},
            timeout=600,
            builder=lambda p: ["subjack", "-w", p["wordlist"], "-t", str(p["threads"]), "-a"],
        ),
    "dirb":     ToolSpec(
            name="dirb",
            binary="dirb",
            description="Directory and file brute forcer",
            params={"url": None, "wordlist": ""},
            timeout=600,
            category="web",
            builder=lambda p: ["dirb", p["url"]] + ([p["wordlist"]] if p["wordlist"] else []),
        ),
    "hakrawler":     ToolSpec(
            name="hakrawler",
            binary="hakrawler",
            description="JS-aware web crawler extracting URLs, domains and emails",
            params={"url": None, "depth": 3},
            timeout=300,
            parser="urls",
            builder=lambda p: ShellCommand(f"echo {shlex.quote(p['url'])} | hakrawler -d {p['depth']} -subs"),
        ),
    "jaeles":     ToolSpec(
            name="jaeles",
            binary="jaeles",
            description="Reusable web vulnerability scanner with signature library",
            params={"url": None},
            timeout=600,
            category="web",
            builder=lambda p: ["jaeles", "scan", "-u", p["url"]],
        ),
    "x8":     ToolSpec(
            name="x8",
            binary="x8",
            description="Hidden parameter discovery via differential response analysis",
            params={"url": None, "words": None},
            timeout=600,
            category="web",
            builder=lambda p: ["x8", "-u", p["url"], "-w", p["words"]],
        ),
    "aquatone":     ToolSpec(
            name="aquatone",
            binary="aquatone",
            description="Visual inspection of websites: screenshots, headers, tech",
            params={"url": None},
            timeout=300,
            category="web",
            builder=lambda p: ["aquatone", "scan", "--url", p["url"]],
        ),
    "tplmap":     ToolSpec(
            name="tplmap",
            binary="tplmap",
            description="Server-side template injection tester",
            params={"url": None},
            timeout=600,
            builder=lambda p: ["tplmap", "-u", p["url"]],
        ),
    "nosqlmap":     ToolSpec(
            name="nosqlmap",
            binary="nosqlmap",
            description="NoSQL injection tester",
            params={"url": None},
            timeout=600,
            builder=lambda p: ["nosqlmap", "-u", p["url"], "--batch"],
        ),
    "wfuzz":     ToolSpec(
            name="wfuzz",
            binary="wfuzz",
            description="Web fuzzer",
            params={"url": None, "wordlist": None, "threads": 40},
            timeout=600,
            builder=lambda p: [
                "wfuzz",
                "-u",
                p["url"].rstrip("/") + "/FUZZ",
                "-w",
                p["wordlist"],
                "--hc",
                "404",
                "-t",
                str(p["threads"]),
            ],
        ),
    "crt_sh":     ToolSpec(
            name="crt_sh",
            binary="curl",
            description="Certificate transparency log search (crt.sh)",
            params={"domain": None},
            timeout=60,
            builder=lambda p: ["curl", "-s", "--max-time", "25", f"https://crt.sh/?q=%25.{p['domain']}&output=json"],
        ),
    "browser_crawl":     ToolSpec(
            name="browser_crawl",
            binary="python",
            description="Headless browser crawl: DOM, JS runtime, screenshots",
            params={"url": None, "wait": 3, "screenshot": False, "dom_depth": 0},
            timeout=120,
            category="web",
            parser="browser_json",
            availability_check=browser_engine_available,
            builder=lambda p: (
                ["python", "-m", "nexhunter.agents.browser_cli", "-u", p["url"], "--wait", str(p["wait"])]
                + (["--screenshot"] if p["screenshot"] else [])
                + (["--dom-depth", str(p["dom_depth"])] if p["dom_depth"] else [])
            ),
        ),
    "webanalyze":     ToolSpec(
            name="webanalyze",
            binary="webanalyze",
            description="Website technology fingerprinting",
            params={"host": None, "update": False},
            timeout=120,
            builder=lambda p: ["webanalyze", "-update"] if p["update"] else ["webanalyze", "-host", p["host"]],
        ),
}
