"""MITRE ATT&CK mapping and remediation knowledge base.

Curated, static tables keyed by CWE and finding category. Deliberately not
generated by a model: a deterministic mapping is auditable, and the model
layer cannot invent a technique the evidence does not support. Unmapped CWEs
get nothing -- a report that lists no technique is honest, one that guesses
is not.
"""

ATTACK_NAMES = {
    "T1040": "Network Sniffing",
    "T1059": "Command and Scripting Interpreter",
    "T1059.007": "Command and Scripting Interpreter: JavaScript",
    "T1078": "Valid Accounts",
    "T1078.001": "Valid Accounts: Default Accounts",
    "T1090": "Proxy",
    "T1110": "Brute Force",
    "T1190": "Exploit Public-Facing Application",
    "T1204.001": "User Execution: Malicious Link",
    "T1210": "Exploitation of Remote Services",
    "T1499": "Endpoint Denial of Service",
    "T1505.003": "Server Software Component: Web Shell",
    "T1555": "Credentials from Password Stores",
    "T1573": "Encrypted Channel",
    "T1005": "Data from Local System",
}

# CWE -> ATT&CK technique the weakness most directly enables.
_CWE_ATTACK = {
    "CWE-77": ("T1059",),
    "CWE-78": ("T1059",),
    "CWE-79": ("T1059.007",),
    "CWE-89": ("T1190",),
    "CWE-94": ("T1059",),
    "CWE-95": ("T1059",),
    "CWE-200": ("T1005",),
    "CWE-209": ("T1005",),
    "CWE-22": ("T1505.003",),
    "CWE-285": ("T1078",),
    "CWE-287": ("T1078",),
    "CWE-306": ("T1078",),
    "CWE-311": ("T1040",),
    "CWE-319": ("T1040",),
    "CWE-326": ("T1573",),
    "CWE-327": ("T1573",),
    "CWE-352": ("T1204.001",),
    "CWE-400": ("T1499",),
    "CWE-434": ("T1505.003",),
    "CWE-502": ("T1210",),
    "CWE-522": ("T1555",),
    "CWE-601": ("T1204.001",),
    "CWE-611": ("T1090",),
    "CWE-770": ("T1499",),
    "CWE-798": ("T1078",),
    "CWE-862": ("T1078",),
    "CWE-863": ("T1078",),
    "CWE-918": ("T1090",),
}

# CWE -> concrete, actionable remediation.
_CWE_REMEDIATION = {
    "CWE-77": "Never build shell commands from input. Use argument-list APIs "
    "without a shell; if a shell is unavoidable, strict allowlist "
    "validation and no string concatenation.",
    "CWE-78": "Never build shell commands from input. Use argument-list APIs "
    "without a shell; if a shell is unavoidable, strict allowlist "
    "validation and no string concatenation.",
    "CWE-79": "Context-aware output encoding for every insertion point (HTML, "
    "attribute, JS, URL); strict allowlist input validation; CSP "
    "without unsafe-inline; sanitize rich content with a maintained "
    "library.",
    "CWE-89": "Parameterized queries or a maintained ORM everywhere; strict "
    "input validation at the boundary; least-privilege database "
    "account; disable stacked queries.",
    "CWE-94": "Never evaluate untrusted input as code. Use safe parsing "
    "libraries and restrict the interpreter's capability surface.",
    "CWE-95": "Never evaluate untrusted input as code. Use safe parsing "
    "libraries and restrict the interpreter's capability surface.",
    "CWE-200": "Minimize data exposed in responses; log details server-side "
    "only; apply strict ACLs on sensitive endpoints.",
    "CWE-209": "Return generic error messages to clients; log the full error server-side only.",
    "CWE-22": "Canonicalize and validate paths against an allowlist; reject "
    "traversal sequences; never join user input into filesystem "
    "paths; use the framework's virtual-path APIs.",
    "CWE-285": "Enforce authorization checks on every resource; default-deny; test with a role-permission matrix.",
    "CWE-287": "Enforce authentication on every sensitive route; MFA for "
    "privileged access; rate-limit login attempts; rotate default "
    "and weak credentials.",
    "CWE-306": "Enforce authentication on every sensitive route; MFA for "
    "privileged access; rate-limit login attempts; rotate default "
    "and weak credentials.",
    "CWE-311": "Encrypt data in transit (TLS 1.2+ with HSTS) and at rest; "
    "never send credentials or tokens over plaintext channels.",
    "CWE-319": "Encrypt data in transit (TLS 1.2+ with HSTS) and at rest; "
    "never send credentials or tokens over plaintext channels.",
    "CWE-326": "Enforce TLS 1.2+ with modern cipher suites (ECDHE, AES-GCM); "
    "disable weak algorithms (RC4, 3DES, MD5, SHA1) and legacy TLS.",
    "CWE-327": "Replace broken cryptographic algorithms (MD5, SHA1, RC4, "
    "3DES) with modern ones; use sufficient key lengths; prefer "
    "vetted libraries over hand-rolled crypto.",
    "CWE-352": "Anti-CSRF token per session (synchronizer pattern or "
    "double-submit cookie); SameSite=Strict cookies; re-verify "
    "sensitive state changes.",
    "CWE-400": "Rate limit and quota request volume; cap body and payload sizes; set resource and connection timeouts.",
    "CWE-434": "Validate extension, MIME, and content server-side; store "
    "uploads outside the web root with random names; serve via an "
    "authenticated download handler; scan with AV.",
    "CWE-502": "Prefer safe formats (JSON) and safe deserializers; sign and "
    "verify serialized payloads; never deserialize untrusted data "
    "with pickle or yaml.load.",
    "CWE-522": "Encrypt stored credentials (KMS/DPAPI-style) and in transit "
    "(TLS 1.2+); restrict decrypt access with least privilege; "
    "audit decrypt paths.",
    "CWE-601": "Validate redirect targets against an allowlist; never reflect "
    "user input into Location headers; treat external redirects as "
    "an explicit decision.",
    "CWE-611": "Disable external entities and DTDs in the XML parser (e.g. "
    "defusedxml, DOCTYPE disabled); prefer JSON; never parse "
    "untrusted XML with parser defaults.",
    "CWE-770": "Rate limit and quota request volume; cap body and payload sizes; set resource and connection timeouts.",
    "CWE-798": "Move secrets to a secrets manager or environment; rotate the "
    "exposed value immediately; add secret scanning to CI; purge "
    "git history.",
    "CWE-862": "Enforce authorization checks on every resource; default-deny; test with a role-permission matrix.",
    "CWE-863": "Enforce authorization checks on every resource; default-deny; test with a role-permission matrix.",
    "CWE-918": "Allowlist outbound destinations; block link-local, private, "
    "and metadata ranges (169.254.169.254); validate scheme and "
    "host; enforce egress with network policy.",
}

# Category fallbacks when no CWE maps.
_CATEGORY_REMEDIATION = {
    "vulnerability": "Apply vendor patches or upgrade to the latest fixed version; verify the fix with a re-scan.",
    "misconfiguration": "Compare the configuration against the vendor "
    "hardening guide or CIS benchmark and apply the "
    "delta.",
    "exposure": "Restrict the exposed service to authorized networks with a "
    "firewall or ACL, enable authentication, and review whether "
    "the service must be public at all.",
    "secret": "Treat the secret as compromised: rotate it, revoke it, remove "
    "it from the codebase and git history, and scan for further "
    "occurrences.",
}


def attack_ids_for(cwe_ids: list[str]) -> list[str]:
    """ATT&CK technique ids for the given CWEs, deduplicated and sorted."""
    out = {technique for cwe in cwe_ids for technique in _CWE_ATTACK.get(cwe, ())}
    return sorted(out)


def attack_name(technique_id: str) -> str | None:
    return ATTACK_NAMES.get(technique_id)


def remediation_for(cwe_ids: list[str], category: str) -> str | None:
    """Concrete remediation: first mapped CWE wins, then the category."""
    for cwe in cwe_ids:
        if cwe in _CWE_REMEDIATION:
            return _CWE_REMEDIATION[cwe]
    return _CATEGORY_REMEDIATION.get(category)
