"""Intelligence agents: CVE lookup, exploit generation."""

import json
import time
import urllib.parse
import urllib.request

from nexhunter.agents.base import Agent

NVD = "https://services.nvd.nist.gov/rest/json/cves/2.0?"

EXPLOIT_KINDS = [
    ("rce", ("remote code execution", "code execution", "command injection", "deserialization", "rce")),
    ("sqli", ("sql injection", "sqli")),
    ("xss", ("cross-site script", "xss", "reflected")),
    ("auth", ("authentication bypass", "auth bypass", "privilege escalation", "authn")),
    ("lfi", ("local file", "path traversal", "directory traversal", "lfi")),
    ("ssrf", ("server-side request forgery", "ssrf")),
]

SCAFFOLD = """# PoC scaffold for {cve} ({kind}) - generated by nexhunter
# IMPORTANT: validate against an AUTHORIZED target only. Not auto-fired.
import requests

TARGET = "http://localhost"  # replace
requests.packages.urllib3.disable_warnings()

def check():
    r = requests.get(TARGET, verify=False, timeout=10)
    print("status:", r.status_code)
    # {hint}
    # expected evidence for this CVE type: {evidence_hint}

if __name__ == "__main__":
    check()
"""


class CVEIntelligenceManager(Agent):
    """CVE lookup and watchlist for detected technologies."""

    name = "cve"
    desc = "NVD CVE lookup + watchlist for detected tech"
    param_schema = {"tech": (False, str)}

    def __init__(self, ctx):
        super().__init__(ctx)
        self._cache = {}
        self._cache_time = {}

    def lookup(self, tech: str, limit: int = 5) -> list:
        """Lookup CVEs for technology."""
        parts = tech.split()
        q = parts[0].lower() + (" " + parts[1] if len(parts) > 1 else "")

        if q in self._cache and (time.time() - self._cache_time.get(q, 0)) < 3600:
            return self._cache[q]

        try:
            url = NVD + urllib.parse.urlencode({"keywordSearch": q, "resultsPerPage": limit})
            req = urllib.request.Request(url, headers={"User-Agent": "nexhunter/1.0"})  # noqa: S310 - NVD API/https only
            with urllib.request.urlopen(req, timeout=6) as resp:  # noqa: S310
                data = json.load(resp)
            out = []
            for v in data.get("vulnerabilities", [])[:limit]:
                c = v["cve"]
                metrics = c.get("metrics") or {}
                cvss = (metrics.get("cvssMetricV31") or metrics.get("cvssMetricV2") or [{}])[0]
                out.append({
                    "id": c["id"],
                    "score": (cvss.get("cvssData") or {}).get("baseScore"),
                    "published": c.get("published", ""),
                    "description": next((d["value"] for d in c.get("descriptions", []) if d.get("lang") == "en"), "")[:200],
                })
            self._cache[q] = out
            self._cache_time[q] = time.time()
            return out
        except Exception as e:
            return [{"error": f"nvd lookup failed: {e}"}]

    def run(self, tech: str = ""):
        """Look up CVEs for technologies."""
        techs = [t.strip() for t in tech.split(",") if t.strip()]
        if not techs:
            return self.result(ok=False, error="tech parameter required")

        by_tech = {t: self.lookup(t) for t in techs}
        flat = [c for lst in by_tech.values() for c in lst if "error" not in c]
        top = sorted(flat, key=lambda c: c.get("score") or 0, reverse=True)[:5]

        return self.result(
            ok=True,
            data={"cves_by_tech": by_tech, "top_critical": top},
            meta={"cache_size": len(self._cache), "techs_searched": len(techs)}
        )


class AIExploitGenerator(Agent):
    """Generate PoC exploit scaffolds for CVEs."""

    name = "exploit"
    desc = "Generate PoC scaffold for a CVE; payload strategy from NVD metadata"
    param_schema = {"cve_id": (True, str)}

    def run(self, cve_id: str = ""):
        """Generate exploit scaffold for CVE."""
        if not cve_id:
            return self.result(ok=False, error="cve_id required")

        try:
            url = NVD + urllib.parse.urlencode({"cveId": cve_id})
            req = urllib.request.Request(url, headers={"User-Agent": "nexhunter/1.0"})  # noqa: S310 - NVD API/https only
            with urllib.request.urlopen(req, timeout=8) as resp:  # noqa: S310
                data = json.load(resp)
            vuls = data.get("vulnerabilities") or []
            if not vuls:
                return self.result(ok=False, error=f"{cve_id} not found in NVD")

            c = vuls[0]["cve"]
            desc = next((d["value"] for d in c.get("descriptions", []) if d.get("lang") == "en"), "")
            low = desc.lower()
            kind = next((k for k, words in EXPLOIT_KINDS if any(w in low for w in words)), "generic")
            hint = {
                "rce": "inject command payload into the parameter/field; observe execution side-effect",
                "sqli": "send ' OR 1=1 -- style payload; watch for changed responses/errors",
                "xss": "reflect <script>alert(1)</script>; confirm in a browser (headless agent optional)",
                "auth": "try alternate roles/tokens/session fixation flows",
                "lfi": "traverse with ../../etc/passwd; look for file content in response",
                "ssrf": "point parameter to http://169.254.169.254 or internal services",
                "generic": "compare patched vs unpatched behavior with a crafted request",
            }[kind]
            return self.result(
                ok=True,
                data={
                    "cve": cve_id,
                    "kind": kind,
                    "summary": desc[:300],
                    "references": [r.get("url") for r in c.get("references", [])],
                    "scaffold": SCAFFOLD.format(cve=cve_id, kind=kind, hint=hint, evidence_hint=kind),
                }
            )
        except Exception as e:
            return self.result(ok=False, error=str(e))
